#ifndef SRC_STARTUP_MATRIX_INPUT_STARTUP_CPP
#define SRC_STARTUP_MATRIX_INPUT_STARTUP_CPP

#include "stm32f0xx.h"

void pinEN(){
    //Enable peripheral clock of pins C,D and F
    RCC->AHBENR |= RCC_AHBENR_GPIODEN;
    RCC -> AHBENR |= RCC_AHBENR_GPIOCEN;
    RCC -> AHBENR |= RCC_AHBENR_GPIOFEN;
    //set pins 0 to 9 of D into output mode
    GPIOD -> MODER = (GPIOA -> MODER & ~(GPIO_MODER_MODER0 | GPIO_MODER_MODER1 | GPIO_MODER_MODER2 | GPIO_MODER_MODER3 |GPIO_MODER_MODER4 | GPIO_MODER_MODER5 |GPIO_MODER_MODER6 | GPIO_MODER_MODER7 | GPIO_MODER_MODER8 | GPIO_MODER_MODER9));
    GPIOD -> MODER |= (GPIO_MODER_MODER0_0 | GPIO_MODER_MODER1_0 | GPIO_MODER_MODER2_0 | GPIO_MODER_MODER3_0 |GPIO_MODER_MODER4_0 | GPIO_MODER_MODER5_0 | GPIO_MODER_MODER6_0 |GPIO_MODER_MODER7_0 | GPIO_MODER_MODER8_0 | GPIO_MODER_MODER9_0);
}



#endif